apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway

spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: marinastancu/gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: SECRET_KEY
            - name: SONGS_MICROSERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: songs
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: bucket
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: region
---
apiVersion: v1
kind: Service
metadata:
  name: gateway

spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080